<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Protectable routes (permission per page)
    | Key = route name, Value = label shown in Permission settings
    | Grouped by section for the UI.
    |--------------------------------------------------------------------------
    */
    'routes' => [
        'Dashboard' => [
            'dashboard' => 'Dashboard',
        ],
        'LBS' => [
            'lbs.add' => 'LBS Add New',
            'lbs.list' => 'LBS List',
            'lbs.completed' => 'LBS Completed',
            'lbs.review' => 'LBS For Review',
            'lbs.mailbox' => 'LBS Mailbox',
            'lbs.trash' => 'LBS Archive',
            'lbs.job.view' => 'LBS View Job',
            'lbs.job.update' => 'LBS Update Job',
            'lbs.job.uploadFiles' => 'LBS Upload Files',
            'lbs.job.deleteFile' => 'LBS Delete File',
            'lbs.job.file' => 'LBS Download File',
            'lbs.job.checkerUploads' => 'LBS Checker Uploads',
            'lbs.job.runComment' => 'LBS Run Comment',
            'lbs.job.comment' => 'LBS Comment',
            'lbs.job.archive' => 'LBS Archive Job',
            'lbs.job.restore' => 'LBS Restore Job',
            'lbs.job.sendSlack' => 'LBS Slack Notify',
            'lbs.job.sendSubmissionEmail' => 'LBS Submission Email',
            'lbs.job.emailPreview' => 'LBS Email Preview',
            'lbs.job.sendMailboxEmail' => 'LBS Send Mailbox Email',
        ],
        'BPH' => [
            'bph.add' => 'BPH Add New',
            'bph.list' => 'BPH List',
            'bph.completed' => 'BPH Completed',
            'bph.review' => 'BPH For Review',
            'bph.mailbox' => 'BPH Mailbox',
            'bph.trash' => 'BPH Archive',
            'bph.store' => 'BPH Save Job',
            'bph.view' => 'BPH View Job',
            'bph.update' => 'BPH Update Job',
            'bph.job.uploadFiles' => 'BPH Upload Files',
            'bph.job.deleteFile' => 'BPH Delete File',
            'bph.job.file' => 'BPH Download File',
            'bph.job.checkerUploads' => 'BPH Checker Uploads',
            'bph.job.runComment' => 'BPH Run Comment',
            'bph.job.comment' => 'BPH Comment',
            'bph.job.archive' => 'BPH Archive',
            'bph.job.mergeFile' => 'BPH Download Print Merge File',
            'bph.job.printCompliance' => 'BPH Print Compliance Summary',
            'bph.job.sendSlack' => 'BPH Slack Notify',
            'bph.job.sendSubmissionEmail' => 'BPH Submission Email',
        ],
        'BPH Email' => [
            'bph_client_email.index' => 'BPH Email — List',
            'bph_client_email.create' => 'BPH Email — Create',
            'bph_client_email.store' => 'BPH Email — Save',
            'bph_client_email.edit' => 'BPH Email — Edit',
            'bph_client_email.update' => 'BPH Email — Update',
            'bph_client_email.destroy' => 'BPH Email — Delete',
        ],
        'CSP' => [
            'csp.add' => 'CSP Add New',
            'csp.store' => 'CSP Save Job',
            'csp.view' => 'CSP View Job',
            'csp.list' => 'CSP List',
            'csp.completed' => 'CSP Completed',
            'csp.review' => 'CSP For Review',
            'csp.mailbox' => 'CSP Mailbox',
            'csp.trash' => 'CSP Archive',
            'csp.update' => 'CSP Update Job',
            'csp.job.emailPreview' => 'CSP Email Preview',
            'csp.job.sendMailboxEmail' => 'CSP Send Mailbox Email',
            'csp.job.printCompliance' => 'CSP Print Compliance Summary',
        ],
        'Bluinq' => [
            'bluinq.add' => 'Bluinq Add New',
            'bluinq.store' => 'Bluinq Save Job',
            'bluinq.view' => 'Bluinq View Job',
            'bluinq.list' => 'Bluinq List',
            'bluinq.completed' => 'Bluinq Completed',
            'bluinq.review' => 'Bluinq For Review',
            'bluinq.mailbox' => 'Bluinq Mailbox',
            'bluinq.trash' => 'Bluinq Archive',
            'bluinq.update' => 'Bluinq Update Job',
            'bluinq.job.sendSlack' => 'Bluinq Slack Notify',
            'bluinq.job.sendSubmissionEmail' => 'Bluinq Submission Email',
            'bluinq.job.emailPreview' => 'Bluinq Email Preview',
            'bluinq.job.sendMailboxEmail' => 'Bluinq Send Mailbox Email',
        ],
        'NH' => [
            'nh.add' => 'NH Add New',
            'nh.store' => 'NH Save Job',
            'nh.list' => 'NH List',
            'nh.completed' => 'NH Completed',
            'nh.review' => 'NH For Review',
            'nh.mailbox' => 'NH Mailbox',
            'nh.trash' => 'NH Archive',
            'nh.update' => 'NH Update Job',
            'nh.job.sendSlack' => 'NH Slack Notify',
            'nh.job.sendSubmissionEmail' => 'NH Submission Email',
            'nh.job.emailPreview' => 'NH Email Preview',
            'nh.job.sendMailboxEmail' => 'NH Send Mailbox Email',
            'nh.job.printCompliance' => 'NH Print Compliance Summary',
        ],
        'LC Home Builder' => [
            'lc_home_builder.add' => 'LC Home Builder Add New',
            'lc_home_builder.store' => 'LC Home Builder Save Job',
            'lc_home_builder.list' => 'LC Home Builder List',
            'lc_home_builder.completed' => 'LC Home Builder Completed',
            'lc_home_builder.review' => 'LC Home Builder For Review',
            'lc_home_builder.mailbox' => 'LC Home Builder Mailbox',
            'lc_home_builder.trash' => 'LC Home Builder Archive',
            'lc_home_builder.update' => 'LC Home Builder Update Job',
            'lc_home_builder.job.sendSlack' => 'LC Home Builder Slack Notify',
            'lc_home_builder.job.sendSubmissionEmail' => 'LC Home Builder Submission Email',
            'lc_home_builder.job.emailPreview' => 'LC Home Builder Email Preview',
            'lc_home_builder.job.sendMailboxEmail' => 'LC Home Builder Send Mailbox Email',
        ],
        'Efficient Living' => [
            'efficient_living.add' => 'Efficient Living Add New',
            'efficient_living.list' => 'Efficient Living List',
            'efficient_living.completed' => 'Efficient Living Completed',
            'efficient_living.review' => 'Efficient Living For Review',
            'efficient_living.mailbox' => 'Efficient Living Mailbox',
            'efficient_living.trash' => 'Efficient Living Archive',
            'efficient_living.job.view' => 'Efficient Living View Job',
            'efficient_living.job.update' => 'Efficient Living Update Job',
            'efficient_living.job.restore' => 'Efficient Living Restore Job',
            'efficient_living.job.emailPreview' => 'Efficient Living Email Preview',
            'efficient_living.job.sendMailboxEmail' => 'Efficient Living Send Mailbox Email',
            'efficient_living.job.sendSlack' => 'Efficient Living Slack Notify',
            'efficient_living.job.sendSubmissionEmail' => 'Efficient Living Submission Email',
        ],
        'Leading Energy' => [
            'leading_energy.add' => 'Leading Energy Add New',
            'leading_energy.store' => 'Leading Energy Save Job',
            'leading_energy.list' => 'Leading Energy List',
            'leading_energy.completed' => 'Leading Energy Completed',
            'leading_energy.review' => 'Leading Energy For Review',
            'leading_energy.mailbox' => 'Leading Energy Mailbox',
            'leading_energy.trash' => 'Leading Energy Archive',
            'leading_energy.update' => 'Leading Energy Update Job',
            'leading_energy.job.sendSlack' => 'Leading Energy Slack Notify',
            'leading_energy.job.sendSubmissionEmail' => 'Leading Energy Submission Email',
            'leading_energy.job.emailPreview' => 'Leading Energy Email Preview',
            'leading_energy.job.sendMailboxEmail' => 'Leading Energy Send Mailbox Email',
        ],
        'Reports' => [
            'reports' => 'Reports',
        ],
        'Settings' => [
            'settings.email_config' => 'Email Configuration',
            'settings.email_config.toggle' => 'Email Sending On/Off',
            'settings.slack_config' => 'Slack Configuration',
            'settings.slack_config.toggle' => 'Slack Notifications On/Off',
            'settings.notifications' => 'Notification Controls Page',
            'settings.permission' => 'Permission',
        ],
        /*
         * UI-only toggles (no HTTP route): which cards appear on the shared job detail page (LBS / Efficient Living / BPH).
         */
        'Job view (cards)' => [
            'job_view.edit.assigned' => 'Job view — Edit assignment (staff & checker)',
            'job_view.card.client_details' => 'Job view — Client Details',
            'job_view.card.job_details' => 'Job view — Job Details',
            'job_view.card.notes' => 'Job view — Notes',
            'job_view.card.complexity' => 'Job view — Complexity',
            'job_view.card.plans' => 'Job view — Plans',
            'job_view.card.documents' => 'Job view — Documents',
            'job_view.card.checker_uploads' => 'Job view — Checker uploads',
            'job_view.card.run_comments' => 'Job view — Run comments',
            'job_view.card.comments' => 'Job view — Comments',
            'job_view.card.activity' => 'Job view — Activity log',
            'job_view.card.bph_additional' => 'Job view — BPH Additional Information',
        ],
        'Job view (buttons)' => [
            'job_view.button.archive_job' => 'Job view — Archive this job button',
            'job_view.button.edit.client_details' => 'Job view — Edit button (Client Details)',
            'job_view.button.edit.job_details' => 'Job view — Edit button (Job Details)',
            'job_view.button.edit.assignment' => 'Job view — Edit button (Assignment)',
            'job_view.button.edit.notes' => 'Job view — Edit button (Notes)',
            'job_view.button.edit.complexity' => 'Job view — Edit complexity stars',
            'job_view.button.files.add' => 'Job view — Add Files button',
            'job_view.button.files.delete' => 'Job view — Delete file button',
            'job_view.button.comments.run.send' => 'Job view — Send Run Comment button',
            'job_view.button.comments.job.send' => 'Job view — Send Comment button',
        ],
        'Job view (per job)' => [
            'job_view.lbs.card.checker_uploads' => 'LBS Job view — Checker Upload Files card',
            'job_view.lbs.button.checker_uploads.add' => 'LBS Job view — Checker Upload Files Add button',
            'job_view.bph.card.checker_uploads' => 'BPH Job view — Checker Upload Files card',
            'job_view.bph.button.checker_uploads.add' => 'BPH Job view — Checker Upload Files Add button',
            'job_view.efficient_living.card.checker_uploads' => 'Efficient Living Job view — Checker Upload Files card',
            'job_view.efficient_living.button.checker_uploads.add' => 'Efficient Living Job view — Checker Upload Files Add button',
        ],
        'Job' => [
            'compliance.index' => 'Compliance',
            'priority.index' => 'Priority',
            'status.index' => 'Status',
            'job_request.index' => 'Job Request',
            'client.index' => 'Client',
        ],
        'Announcement' => [
            'announcement.index' => 'Announcement List',
            'announcement.create' => 'Announcement Create Page',
            'announcement.store' => 'Announcement Save New',
            'announcement.edit' => 'Announcement Edit Page',
            'announcement.update' => 'Announcement Save Update',
            'announcement.destroy' => 'Announcement Delete',
        ],
        'Branch offices' => [
            'branch.index' => 'Branch List',
            'branch.archive' => 'Branch Archive',
        ],
        'Accounts' => [
            'users.index' => 'User Accounts',
            'accounts.clients.index' => 'Client Accounts',
            'users.archive' => 'User Archive',
        ],
        'Account' => [
            'account.settings.edit' => 'My Account Settings',
        ],
    ],

    'roles' => ['Admin', 'Branch', 'Staff', 'Checker', 'User'],

    /*
    |--------------------------------------------------------------------------
    | Permission UI: section cards grouped like the sidebar (Job management, …)
    |--------------------------------------------------------------------------
    */
    'route_display' => [
        ['heading' => null, 'sections' => ['Dashboard']],
        ['heading' => 'Job management', 'sections' => [
            'LBS',
            'BPH',
            'BPH Email',
            'Efficient Living',
            'Bluinq',
            'CSP',
            'NH',
            'LC Home Builder',
            'Leading Energy',
        ]],
        ['heading' => 'Job view & master data', 'sections' => ['Job view (cards)', 'Job view (buttons)', 'Job view (per job)', 'Job', 'Announcement']],
        ['heading' => 'Reports & settings', 'sections' => ['Reports', 'Settings']],
        ['heading' => 'Branches & accounts', 'sections' => ['Branch offices', 'Accounts', 'Account']],
    ],
];
