<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Protectable routes (permission per page)
    | Key = route name, Value = label shown in Permission settings
    | Grouped by section for the UI.
    |--------------------------------------------------------------------------
    */
    'routes' => [
        'Dashboard' => [
            'dashboard' => 'Dashboard',
        ],
        'LBS' => [
            'lbs.add' => 'LBS Add New',
            'lbs.list' => 'LBS List',
            'lbs.completed' => 'LBS Completed',
            'lbs.review' => 'LBS For Review',
            'lbs.mailbox' => 'LBS Mailbox',
            'lbs.trash' => 'LBS Archive',
            'lbs.job.view' => 'LBS View Job',
            'lbs.job.update' => 'LBS Update Job',
            'lbs.job.uploadFiles' => 'LBS Add Job Files',
            'lbs.job.deleteFile' => 'LBS Delete File',
            'lbs.job.file' => 'LBS Download File',
            'lbs.job.checkerUploads' => 'LBS Checker Add Files',
            'lbs.job.runComment' => 'LBS Run Comment',
            'lbs.job.comment' => 'LBS Comment',
            'lbs.job.archive' => 'LBS Archive Job',
            'lbs.job.restore' => 'LBS Restore Job',
            'lbs.job.sendSlack' => 'LBS Slack Notify',
            'lbs.job.sendSubmissionEmail' => 'LBS Submission Email',
            'lbs.job.emailPreview' => 'LBS Email Preview',
            'lbs.job.sendMailboxEmail' => 'LBS Send Mailbox Email',
        ],
        'BPH' => [
            'bph.add' => 'BPH Add New',
            'bph.list' => 'BPH List',
            'bph.completed' => 'BPH Completed',
            'bph.review' => 'BPH For Review',
            'bph.mailbox' => 'BPH Mailbox',
            'bph.trash' => 'BPH Archive',
            'bph.store' => 'BPH Save Job',
            'bph.view' => 'BPH View Job',
            'bph.update' => 'BPH Update Job',
            'bph.job.uploadFiles' => 'BPH Add Job Files',
            'bph.job.deleteFile' => 'BPH Delete File',
            'bph.job.file' => 'BPH Download File',
            'bph.job.checkerUploads' => 'BPH Checker Add Files',
            'bph.job.runComment' => 'BPH Run Comment',
            'bph.job.comment' => 'BPH Comment',
            'bph.job.archive' => 'BPH Archive',
            'bph.job.mergeFile' => 'BPH Download Print Merge File',
            'bph.job.printCompliance' => 'BPH Print Compliance Summary',
            'bph.job.sendSlack' => 'BPH Slack Notify',
            'bph.job.sendSubmissionEmail' => 'BPH Submission Email',
        ],
        'BPH Email' => [
            'bph_client_email.index' => 'BPH Email — List',
            'bph_client_email.create' => 'BPH Email — Create',
            'bph_client_email.store' => 'BPH Email — Save',
            'bph_client_email.edit' => 'BPH Email — Edit',
            'bph_client_email.update' => 'BPH Email — Update',
            'bph_client_email.destroy' => 'BPH Email — Delete',
        ],
        'CSP' => [
            'csp.add' => 'CSP Add New',
            'csp.store' => 'CSP Save Job',
            'csp.view' => 'CSP View Job',
            'csp.list' => 'CSP List',
            'csp.completed' => 'CSP Completed',
            'csp.review' => 'CSP For Review',
            'csp.mailbox' => 'CSP Mailbox',
            'csp.trash' => 'CSP Archive',
            'csp.update' => 'CSP Update Job',
            'csp.job.emailPreview' => 'CSP Email Preview',
            'csp.job.sendMailboxEmail' => 'CSP Send Mailbox Email',
            'csp.job.printCompliance' => 'CSP Print Compliance Summary',
        ],
        'Bluinq' => [
            'bluinq.add' => 'Bluinq Add New',
            'bluinq.store' => 'Bluinq Save Job',
            'bluinq.view' => 'Bluinq View Job',
            'bluinq.list' => 'Bluinq List',
            'bluinq.completed' => 'Bluinq Completed',
            'bluinq.review' => 'Bluinq For Review',
            'bluinq.mailbox' => 'Bluinq Mailbox',
            'bluinq.trash' => 'Bluinq Archive',
            'bluinq.update' => 'Bluinq Update Job',
            'bluinq.job.sendSlack' => 'Bluinq Slack Notify',
            'bluinq.job.sendSubmissionEmail' => 'Bluinq Submission Email',
            'bluinq.job.emailPreview' => 'Bluinq Email Preview',
            'bluinq.job.sendMailboxEmail' => 'Bluinq Send Mailbox Email',
        ],
        'NH' => [
            'nh.add' => 'NH Add New',
            'nh.store' => 'NH Save Job',
            'nh.list' => 'NH List',
            'nh.completed' => 'NH Completed',
            'nh.review' => 'NH For Review',
            'nh.mailbox' => 'NH Mailbox',
            'nh.trash' => 'NH Archive',
            'nh.update' => 'NH Update Job',
            'nh.job.sendSlack' => 'NH Slack Notify',
            'nh.job.sendSubmissionEmail' => 'NH Submission Email',
            'nh.job.emailPreview' => 'NH Email Preview',
            'nh.job.sendMailboxEmail' => 'NH Send Mailbox Email',
            'nh.job.printCompliance' => 'NH Print Compliance Summary',
        ],
        'LC Home Builder' => [
            'lc_home_builder.add' => 'LC Home Builder Add New',
            'lc_home_builder.store' => 'LC Home Builder Save Job',
            'lc_home_builder.list' => 'LC Home Builder List',
            'lc_home_builder.completed' => 'LC Home Builder Completed',
            'lc_home_builder.review' => 'LC Home Builder For Review',
            'lc_home_builder.mailbox' => 'LC Home Builder Mailbox',
            'lc_home_builder.trash' => 'LC Home Builder Archive',
            'lc_home_builder.update' => 'LC Home Builder Update Job',
            'lc_home_builder.job.sendSlack' => 'LC Home Builder Slack Notify',
            'lc_home_builder.job.sendSubmissionEmail' => 'LC Home Builder Submission Email',
            'lc_home_builder.job.emailPreview' => 'LC Home Builder Email Preview',
            'lc_home_builder.job.sendMailboxEmail' => 'LC Home Builder Send Mailbox Email',
        ],
        'Efficient Living' => [
            'efficient_living.add' => 'Efficient Living Add New',
            'efficient_living.list' => 'Efficient Living List',
            'efficient_living.completed' => 'Efficient Living Completed',
            'efficient_living.review' => 'Efficient Living For Review',
            'efficient_living.mailbox' => 'Efficient Living Mailbox',
            'efficient_living.trash' => 'Efficient Living Archive',
            'efficient_living.job.view' => 'Efficient Living View Job',
            'efficient_living.job.update' => 'Efficient Living Update Job',
            'efficient_living.job.restore' => 'Efficient Living Restore Job',
            'efficient_living.job.emailPreview' => 'Efficient Living Email Preview',
            'efficient_living.job.sendMailboxEmail' => 'Efficient Living Send Mailbox Email',
            'efficient_living.job.sendSlack' => 'Efficient Living Slack Notify',
            'efficient_living.job.sendSubmissionEmail' => 'Efficient Living Submission Email',
        ],
        'Leading Energy' => [
            'leading_energy.add' => 'Leading Energy Add New',
            'leading_energy.store' => 'Leading Energy Save Job',
            'leading_energy.view' => 'Leading Energy View Job',
            'leading_energy.list' => 'Leading Energy List',
            'leading_energy.completed' => 'Leading Energy Completed',
            'leading_energy.review' => 'Leading Energy For Review',
            'leading_energy.mailbox' => 'Leading Energy Mailbox',
            'leading_energy.trash' => 'Leading Energy Archive',
            'leading_energy.update' => 'Leading Energy Update Job',
            'leading_energy.job.sendSlack' => 'Leading Energy Slack Notify',
            'leading_energy.job.sendSubmissionEmail' => 'Leading Energy Submission Email',
            'leading_energy.job.emailPreview' => 'Leading Energy Email Preview',
            'leading_energy.job.sendMailboxEmail' => 'Leading Energy Send Mailbox Email',
        ],
        'Reports' => [
            'reports' => 'Reports',
        ],
        'Settings' => [
            'settings.email_config' => 'Email Configuration',
            'settings.email_config.toggle' => 'Email Sending On/Off',
            'settings.slack_config' => 'Slack Configuration',
            'settings.slack_config.toggle' => 'Slack Notifications On/Off',
            'settings.notifications' => 'Notification Controls Page',
            'settings.permission' => 'Permission',
        ],
        /*
         * UI-only toggles (no HTTP route): job detail cards and actions, scoped per product line (LBS / BPH / Efficient Living).
         */
        'Job view (LBS)' => [
            'job_view.lbs.edit_assigned' => 'LBS — Edit assignment',
            'job_view.lbs.card.client_details' => 'LBS — Client Details card',
            'job_view.lbs.card.job_details' => 'LBS — Job Details card',
            'job_view.lbs.card.notes' => 'LBS — Notes card',
            'job_view.lbs.card.complexity' => 'LBS — Complexity card',
            'job_view.lbs.card.plans' => 'LBS — Plans card',
            'job_view.lbs.card.documents' => 'LBS — Documents card',
            'job_view.lbs.card.checker_uploads' => 'LBS — Checker Add Files card',
            'job_view.lbs.card.run_comments' => 'LBS — Run Comments card',
            'job_view.lbs.card.comments' => 'LBS — Comments card',
            'job_view.lbs.card.activity' => 'LBS — Activity Log card',
            'job_view.lbs.button.archive_job' => 'LBS — Archive this job',
            'job_view.lbs.button.edit.client_details' => 'LBS — Edit (Client Details)',
            'job_view.lbs.button.edit.job_details' => 'LBS — Edit (Job Details)',
            'job_view.lbs.button.edit.assignment' => 'LBS — Edit (Assignment)',
            'job_view.lbs.button.edit.notes' => 'LBS — Edit (Notes)',
            'job_view.lbs.button.edit.complexity' => 'LBS — Edit complexity stars',
            'job_view.lbs.button.files.add' => 'LBS — Add job files',
            'job_view.lbs.button.files.delete' => 'LBS — Delete file',
            'job_view.lbs.button.comments.run.send' => 'LBS — Send run comment',
            'job_view.lbs.button.comments.job.send' => 'LBS — Send comment',
            'job_view.lbs.button.checker_uploads.add' => 'LBS — Checker add files',
        ],
        'Job view (BPH)' => [
            'job_view.bph.edit_assigned' => 'BPH — Edit assignment',
            'job_view.bph.card.client_details' => 'BPH — Client Details card',
            'job_view.bph.card.job_details' => 'BPH — Job Details card',
            'job_view.bph.card.notes' => 'BPH — Notes card',
            'job_view.bph.card.complexity' => 'BPH — Complexity card',
            'job_view.bph.card.plans' => 'BPH — Plans card',
            'job_view.bph.card.documents' => 'BPH — Documents card',
            'job_view.bph.card.checker_uploads' => 'BPH — Checker Add Files card',
            'job_view.bph.card.run_comments' => 'BPH — Run Comments card',
            'job_view.bph.card.comments' => 'BPH — Comments card',
            'job_view.bph.card.activity' => 'BPH — Activity Log card',
            'job_view.bph.card.bph_additional' => 'BPH — Additional Information card',
            'job_view.bph.button.archive_job' => 'BPH — Archive this job',
            'job_view.bph.button.edit.client_details' => 'BPH — Edit (Client Details)',
            'job_view.bph.button.edit.job_details' => 'BPH — Edit (Job Details)',
            'job_view.bph.button.edit.assignment' => 'BPH — Edit (Assignment)',
            'job_view.bph.button.edit.notes' => 'BPH — Edit (Notes)',
            'job_view.bph.button.edit.complexity' => 'BPH — Edit complexity stars',
            'job_view.bph.button.files.add' => 'BPH — Add job files',
            'job_view.bph.button.files.delete' => 'BPH — Delete file',
            'job_view.bph.button.comments.run.send' => 'BPH — Send run comment',
            'job_view.bph.button.comments.job.send' => 'BPH — Send comment',
            'job_view.bph.button.checker_uploads.add' => 'BPH — Checker add files',
        ],
        'Job view (Efficient Living)' => [
            'job_view.efficient_living.edit_assigned' => 'Efficient Living — Edit assignment',
            'job_view.efficient_living.card.client_details' => 'Efficient Living — Client Details card',
            'job_view.efficient_living.card.job_details' => 'Efficient Living — Job Details card',
            'job_view.efficient_living.card.notes' => 'Efficient Living — Notes card',
            'job_view.efficient_living.card.complexity' => 'Efficient Living — Complexity card',
            'job_view.efficient_living.card.plans' => 'Efficient Living — Plans card',
            'job_view.efficient_living.card.documents' => 'Efficient Living — Documents card',
            'job_view.efficient_living.card.checker_uploads' => 'Efficient Living — Checker Add Files card',
            'job_view.efficient_living.card.run_comments' => 'Efficient Living — Run Comments card',
            'job_view.efficient_living.card.comments' => 'Efficient Living — Comments card',
            'job_view.efficient_living.card.activity' => 'Efficient Living — Activity Log card',
            'job_view.efficient_living.button.archive_job' => 'Efficient Living — Archive this job',
            'job_view.efficient_living.button.edit.client_details' => 'Efficient Living — Edit (Client Details)',
            'job_view.efficient_living.button.edit.job_details' => 'Efficient Living — Edit (Job Details)',
            'job_view.efficient_living.button.edit.assignment' => 'Efficient Living — Edit (Assignment)',
            'job_view.efficient_living.button.edit.notes' => 'Efficient Living — Edit (Notes)',
            'job_view.efficient_living.button.edit.complexity' => 'Efficient Living — Edit complexity stars',
            'job_view.efficient_living.button.files.add' => 'Efficient Living — Add job files',
            'job_view.efficient_living.button.files.delete' => 'Efficient Living — Delete file',
            'job_view.efficient_living.button.comments.run.send' => 'Efficient Living — Send run comment',
            'job_view.efficient_living.button.comments.job.send' => 'Efficient Living — Send comment',
            'job_view.efficient_living.button.checker_uploads.add' => 'Efficient Living — Checker add files',
        ],
        'Job view (Bluinq)' => [
            'job_view.bluinq.card.client_details' => 'Bluinq — Client Details card',
            'job_view.bluinq.card.job_details' => 'Bluinq — Job Details card',
            'job_view.bluinq.card.notes' => 'Bluinq — Notes card',
            'job_view.bluinq.card.complexity' => 'Bluinq — Complexity card',
            'job_view.bluinq.card.plans' => 'Bluinq — Plans card',
            'job_view.bluinq.card.documents' => 'Bluinq — Documents card',
            'job_view.bluinq.card.checker_uploads' => 'Bluinq — Checker Add Files card',
            'job_view.bluinq.card.run_comments' => 'Bluinq — Run Comments card',
            'job_view.bluinq.card.comments' => 'Bluinq — Comments card',
            'job_view.bluinq.card.activity' => 'Bluinq — Activity Log card',
        ],
        'Job view (CSP)' => [
            'job_view.csp.card.client_details' => 'CSP — Client Details card',
            'job_view.csp.card.job_details' => 'CSP — Job Details card',
            'job_view.csp.card.notes' => 'CSP — Notes card',
            'job_view.csp.card.complexity' => 'CSP — Complexity card',
            'job_view.csp.card.plans' => 'CSP — Plans card',
            'job_view.csp.card.documents' => 'CSP — Documents card',
            'job_view.csp.card.checker_uploads' => 'CSP — Checker Add Files card',
            'job_view.csp.card.run_comments' => 'CSP — Run Comments card',
            'job_view.csp.card.comments' => 'CSP — Comments card',
            'job_view.csp.card.activity' => 'CSP — Activity Log card',
        ],
        'Job view (NH)' => [
            'job_view.nh.card.client_details' => 'NH — Client Details card',
            'job_view.nh.card.job_details' => 'NH — Job Details card',
            'job_view.nh.card.notes' => 'NH — Notes card',
            'job_view.nh.card.complexity' => 'NH — Complexity card',
            'job_view.nh.card.plans' => 'NH — Plans card',
            'job_view.nh.card.documents' => 'NH — Documents card',
            'job_view.nh.card.checker_uploads' => 'NH — Checker Add Files card',
            'job_view.nh.card.run_comments' => 'NH — Run Comments card',
            'job_view.nh.card.comments' => 'NH — Comments card',
            'job_view.nh.card.activity' => 'NH — Activity Log card',
        ],
        'Job view (LC Home Builder)' => [
            'job_view.lc_home_builder.card.client_details' => 'LC Home Builder — Client Details card',
            'job_view.lc_home_builder.card.job_details' => 'LC Home Builder — Job Details card',
            'job_view.lc_home_builder.card.notes' => 'LC Home Builder — Notes card',
            'job_view.lc_home_builder.card.complexity' => 'LC Home Builder — Complexity card',
            'job_view.lc_home_builder.card.plans' => 'LC Home Builder — Plans card',
            'job_view.lc_home_builder.card.documents' => 'LC Home Builder — Documents card',
            'job_view.lc_home_builder.card.checker_uploads' => 'LC Home Builder — Checker Add Files card',
            'job_view.lc_home_builder.card.run_comments' => 'LC Home Builder — Run Comments card',
            'job_view.lc_home_builder.card.comments' => 'LC Home Builder — Comments card',
            'job_view.lc_home_builder.card.activity' => 'LC Home Builder — Activity Log card',
        ],
        'Job view (Leading Energy)' => [
            'job_view.leading_energy.card.client_details' => 'Leading Energy — Client Details card',
            'job_view.leading_energy.card.job_details' => 'Leading Energy — Job Details card',
            'job_view.leading_energy.card.notes' => 'Leading Energy — Notes card',
            'job_view.leading_energy.card.complexity' => 'Leading Energy — Complexity card',
            'job_view.leading_energy.card.plans' => 'Leading Energy — Plans card',
            'job_view.leading_energy.card.documents' => 'Leading Energy — Documents card',
            'job_view.leading_energy.card.checker_uploads' => 'Leading Energy — Checker Add Files card',
            'job_view.leading_energy.card.run_comments' => 'Leading Energy — Run Comments card',
            'job_view.leading_energy.card.comments' => 'Leading Energy — Comments card',
            'job_view.leading_energy.card.activity' => 'Leading Energy — Activity Log card',
        ],
        'Job' => [
            'compliance.index' => 'Compliance',
            'priority.index' => 'Priority',
            'status.index' => 'Status',
            'job_request.index' => 'Job Request',
            'client.index' => 'Client',
        ],
        'Announcement' => [
            'announcement.index' => 'Announcement List',
            'announcement.create' => 'Announcement Create Page',
            'announcement.store' => 'Announcement Save New',
            'announcement.edit' => 'Announcement Edit Page',
            'announcement.update' => 'Announcement Save Update',
            'announcement.destroy' => 'Announcement Delete',
        ],
        'Branch offices' => [
            'branch.index' => 'Branch List',
            'branch.archive' => 'Branch Archive',
        ],
        'Accounts' => [
            'users.index' => 'User Accounts',
            'accounts.clients.index' => 'Client Accounts',
            'users.archive' => 'User Archive',
        ],
        'Account' => [
            'account.settings.edit' => 'My Account Settings',
        ],
    ],

    'roles' => ['Admin', 'Branch', 'Staff', 'Checker', 'User'],

    /*
    |--------------------------------------------------------------------------
    | Permission settings UI: stacked job areas, three columns each. Each route
    | appears in exactly one module. LBS / BPH / Efficient Living each have their
    | own job-page cards and buttons (no shared “one block for all” mirror).
    |--------------------------------------------------------------------------
    */
    'job_ui_modules' => [
        'lbs' => [
            'label' => 'LBS',
            'sidebar' => [
                'lbs.add', 'lbs.list', 'lbs.completed', 'lbs.review', 'lbs.mailbox', 'lbs.trash', 'lbs.job.view',
                'job_view.lbs.edit_assigned',
            ],
            'card' => [
                'job_view.lbs.card.client_details',
                'job_view.lbs.card.job_details',
                'job_view.lbs.card.notes',
                'job_view.lbs.card.complexity',
                'job_view.lbs.card.plans',
                'job_view.lbs.card.documents',
                'job_view.lbs.card.checker_uploads',
                'job_view.lbs.card.run_comments',
                'job_view.lbs.card.comments',
                'job_view.lbs.card.activity',
            ],
            'buttons' => [
                'lbs.job.update', 'lbs.job.uploadFiles', 'lbs.job.deleteFile', 'lbs.job.file', 'lbs.job.checkerUploads',
                'lbs.job.runComment', 'lbs.job.comment', 'lbs.job.archive', 'lbs.job.restore', 'lbs.job.sendSlack',
                'lbs.job.sendSubmissionEmail', 'lbs.job.emailPreview', 'lbs.job.sendMailboxEmail',
                'job_view.lbs.button.archive_job',
                'job_view.lbs.button.edit.client_details',
                'job_view.lbs.button.edit.job_details',
                'job_view.lbs.button.edit.assignment',
                'job_view.lbs.button.edit.notes',
                'job_view.lbs.button.edit.complexity',
                'job_view.lbs.button.files.add',
                'job_view.lbs.button.files.delete',
                'job_view.lbs.button.comments.run.send',
                'job_view.lbs.button.comments.job.send',
                'job_view.lbs.button.checker_uploads.add',
            ],
        ],
        'bph' => [
            'label' => 'BPH',
            'sidebar' => [
                'bph.add', 'bph.list', 'bph.completed', 'bph.review', 'bph.mailbox', 'bph.trash',
                'bph.store', 'bph.view', 'bph.update',
                'job_view.bph.edit_assigned',
            ],
            'card' => [
                'job_view.bph.card.client_details',
                'job_view.bph.card.job_details',
                'job_view.bph.card.notes',
                'job_view.bph.card.complexity',
                'job_view.bph.card.plans',
                'job_view.bph.card.documents',
                'job_view.bph.card.checker_uploads',
                'job_view.bph.card.run_comments',
                'job_view.bph.card.comments',
                'job_view.bph.card.activity',
                'job_view.bph.card.bph_additional',
            ],
            'buttons' => [
                'bph.job.uploadFiles', 'bph.job.deleteFile', 'bph.job.file', 'bph.job.checkerUploads',
                'bph.job.runComment', 'bph.job.comment', 'bph.job.archive', 'bph.job.mergeFile', 'bph.job.printCompliance',
                'bph.job.sendSlack', 'bph.job.sendSubmissionEmail',
                'job_view.bph.button.archive_job',
                'job_view.bph.button.edit.client_details',
                'job_view.bph.button.edit.job_details',
                'job_view.bph.button.edit.assignment',
                'job_view.bph.button.edit.notes',
                'job_view.bph.button.edit.complexity',
                'job_view.bph.button.files.add',
                'job_view.bph.button.files.delete',
                'job_view.bph.button.comments.run.send',
                'job_view.bph.button.comments.job.send',
                'job_view.bph.button.checker_uploads.add',
            ],
        ],
        'bph_email' => [
            'label' => 'BPH Email',
            'sidebar' => [
                'bph_client_email.index', 'bph_client_email.create', 'bph_client_email.store',
                'bph_client_email.edit', 'bph_client_email.update', 'bph_client_email.destroy',
            ],
            'card' => [],
            'buttons' => [],
        ],
        'efficient_living' => [
            'label' => 'Efficient Living',
            'sidebar' => [
                'efficient_living.add', 'efficient_living.list', 'efficient_living.completed', 'efficient_living.review',
                'efficient_living.mailbox', 'efficient_living.trash', 'efficient_living.job.view',
                'job_view.efficient_living.edit_assigned',
            ],
            'card' => [
                'job_view.efficient_living.card.client_details',
                'job_view.efficient_living.card.job_details',
                'job_view.efficient_living.card.notes',
                'job_view.efficient_living.card.complexity',
                'job_view.efficient_living.card.plans',
                'job_view.efficient_living.card.documents',
                'job_view.efficient_living.card.checker_uploads',
                'job_view.efficient_living.card.run_comments',
                'job_view.efficient_living.card.comments',
                'job_view.efficient_living.card.activity',
            ],
            'buttons' => [
                'efficient_living.job.update', 'efficient_living.job.restore', 'efficient_living.job.emailPreview',
                'efficient_living.job.sendMailboxEmail', 'efficient_living.job.sendSlack', 'efficient_living.job.sendSubmissionEmail',
                'job_view.efficient_living.button.archive_job',
                'job_view.efficient_living.button.edit.client_details',
                'job_view.efficient_living.button.edit.job_details',
                'job_view.efficient_living.button.edit.assignment',
                'job_view.efficient_living.button.edit.notes',
                'job_view.efficient_living.button.edit.complexity',
                'job_view.efficient_living.button.files.add',
                'job_view.efficient_living.button.files.delete',
                'job_view.efficient_living.button.comments.run.send',
                'job_view.efficient_living.button.comments.job.send',
                'job_view.efficient_living.button.checker_uploads.add',
            ],
        ],
        'bluinq' => [
            'label' => 'Bluinq',
            'sidebar' => [
                'bluinq.add', 'bluinq.store', 'bluinq.view', 'bluinq.list', 'bluinq.completed', 'bluinq.review',
                'bluinq.mailbox', 'bluinq.trash', 'bluinq.update',
            ],
            'card' => [
                'job_view.bluinq.card.client_details',
                'job_view.bluinq.card.job_details',
                'job_view.bluinq.card.notes',
                'job_view.bluinq.card.complexity',
                'job_view.bluinq.card.plans',
                'job_view.bluinq.card.documents',
                'job_view.bluinq.card.checker_uploads',
                'job_view.bluinq.card.run_comments',
                'job_view.bluinq.card.comments',
                'job_view.bluinq.card.activity',
            ],
            'buttons' => [
                'bluinq.job.sendSlack', 'bluinq.job.sendSubmissionEmail', 'bluinq.job.emailPreview', 'bluinq.job.sendMailboxEmail',
            ],
        ],
        'csp' => [
            'label' => 'CSP',
            'sidebar' => [
                'csp.add', 'csp.store', 'csp.view', 'csp.list', 'csp.completed', 'csp.review', 'csp.mailbox', 'csp.trash', 'csp.update',
            ],
            'card' => [
                'job_view.csp.card.client_details',
                'job_view.csp.card.job_details',
                'job_view.csp.card.notes',
                'job_view.csp.card.complexity',
                'job_view.csp.card.plans',
                'job_view.csp.card.documents',
                'job_view.csp.card.checker_uploads',
                'job_view.csp.card.run_comments',
                'job_view.csp.card.comments',
                'job_view.csp.card.activity',
            ],
            'buttons' => [
                'csp.job.emailPreview', 'csp.job.sendMailboxEmail', 'csp.job.printCompliance',
            ],
        ],
        'nh' => [
            'label' => 'NH',
            'sidebar' => [
                'nh.add', 'nh.store', 'nh.list', 'nh.completed', 'nh.review', 'nh.mailbox', 'nh.trash', 'nh.update',
            ],
            'card' => [
                'job_view.nh.card.client_details',
                'job_view.nh.card.job_details',
                'job_view.nh.card.notes',
                'job_view.nh.card.complexity',
                'job_view.nh.card.plans',
                'job_view.nh.card.documents',
                'job_view.nh.card.checker_uploads',
                'job_view.nh.card.run_comments',
                'job_view.nh.card.comments',
                'job_view.nh.card.activity',
            ],
            'buttons' => [
                'nh.job.sendSlack', 'nh.job.sendSubmissionEmail', 'nh.job.emailPreview', 'nh.job.sendMailboxEmail', 'nh.job.printCompliance',
            ],
        ],
        'lc_home_builder' => [
            'label' => 'LC Home Builder',
            'sidebar' => [
                'lc_home_builder.add', 'lc_home_builder.store', 'lc_home_builder.list', 'lc_home_builder.completed',
                'lc_home_builder.review', 'lc_home_builder.mailbox', 'lc_home_builder.trash', 'lc_home_builder.update',
            ],
            'card' => [
                'job_view.lc_home_builder.card.client_details',
                'job_view.lc_home_builder.card.job_details',
                'job_view.lc_home_builder.card.notes',
                'job_view.lc_home_builder.card.complexity',
                'job_view.lc_home_builder.card.plans',
                'job_view.lc_home_builder.card.documents',
                'job_view.lc_home_builder.card.checker_uploads',
                'job_view.lc_home_builder.card.run_comments',
                'job_view.lc_home_builder.card.comments',
                'job_view.lc_home_builder.card.activity',
            ],
            'buttons' => [
                'lc_home_builder.job.sendSlack', 'lc_home_builder.job.sendSubmissionEmail',
                'lc_home_builder.job.emailPreview', 'lc_home_builder.job.sendMailboxEmail',
            ],
        ],
        'leading_energy' => [
            'label' => 'Leading Energy',
            'sidebar' => [
                'leading_energy.add', 'leading_energy.store', 'leading_energy.list', 'leading_energy.completed',
                'leading_energy.review', 'leading_energy.mailbox', 'leading_energy.trash', 'leading_energy.view', 'leading_energy.update',
            ],
            'card' => [
                'job_view.leading_energy.card.client_details',
                'job_view.leading_energy.card.job_details',
                'job_view.leading_energy.card.notes',
                'job_view.leading_energy.card.complexity',
                'job_view.leading_energy.card.plans',
                'job_view.leading_energy.card.documents',
                'job_view.leading_energy.card.checker_uploads',
                'job_view.leading_energy.card.run_comments',
                'job_view.leading_energy.card.comments',
                'job_view.leading_energy.card.activity',
            ],
            'buttons' => [
                'leading_energy.job.sendSlack', 'leading_energy.job.sendSubmissionEmail',
                'leading_energy.job.emailPreview', 'leading_energy.job.sendMailboxEmail',
            ],
        ],
        'other' => [
            'label' => 'Other (dashboard, reports, settings, …)',
            'sidebar' => [
                'dashboard', 'reports',
                'settings.email_config', 'settings.email_config.toggle', 'settings.slack_config', 'settings.slack_config.toggle',
                'settings.notifications', 'settings.permission',
                'compliance.index', 'priority.index', 'status.index', 'job_request.index', 'client.index',
                'announcement.index', 'announcement.create', 'announcement.store', 'announcement.edit', 'announcement.update', 'announcement.destroy',
                'branch.index', 'branch.archive',
                'users.index', 'accounts.clients.index', 'users.archive',
                'account.settings.edit',
            ],
            'card' => [],
            'buttons' => [],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Permission UI: section cards grouped like the sidebar (Job management, …)
    |--------------------------------------------------------------------------
    */
    'route_display' => [
        ['heading' => null, 'sections' => ['Dashboard']],
        ['heading' => 'Job management', 'sections' => [
            'LBS',
            'BPH',
            'BPH Email',
            'Efficient Living',
            'Bluinq',
            'CSP',
            'NH',
            'LC Home Builder',
            'Leading Energy',
        ]],
        ['heading' => 'Job view & master data', 'sections' => ['Job view (LBS)', 'Job view (BPH)', 'Job view (Efficient Living)', 'Job view (Bluinq)', 'Job view (CSP)', 'Job view (NH)', 'Job view (LC Home Builder)', 'Job view (Leading Energy)', 'Job', 'Announcement']],
        ['heading' => 'Reports & settings', 'sections' => ['Reports', 'Settings']],
        ['heading' => 'Branches & accounts', 'sections' => ['Branch offices', 'Accounts', 'Account']],
    ],
];
